from pathlib import Path
import json,hashlib,shutil
repo=Path('/Users/mikkokotila/dev/Dra-Thal-Gyur');w=Path(__file__).parent;prefix='signs-recovery-review-20260927';out=repo/'diplomatic/reviews/chapter-01';ev=repo/'diplomatic/evidence/chapter-01'/prefix
report=json.loads((out/f'{prefix}.json').read_text());proposals=json.loads((out/f'{prefix}-additional-interventions.proposed.json').read_text());units={x['id']:x for x in json.loads((repo/'diplomatic/collation/chapter-01/reading-units.json').read_text())};imgmeta=json.loads((repo/'editions/adzom-2000/image-manifest.json').read_text());cropmeta=json.loads((w/'second-five-crops.json').read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
notes={
'U00578':('two detached shads after dri: the first follows the final syllable, the second stands before ston; neither is a letter downstroke.','AS-E-019.png'),
'U00594':("two detached shads after 'byin before ston; the first immediately follows the final letter and the second is separated by a blank interval.",'AS-E-020.png'),
'U00710':('a discrete tsheg is visible between final nga of gang and the first of two detached shads. Restore this local tsheg while retaining the prior separation of the small source annotation from the main verse.','AS-E-023.png'),
'U01757':("two detached shads after 'gyur before rang ngo; the curved lower letter/vowel strokes are separate from these vertical delimiters.",None),
'U02080':('two detached shads after ni before gsal. The second upright is detached from the following ga body; the lower neighboring curved stroke is not counted as a shad.',None)
}
for ident,(observed,prior) in notes.items():
 assert ident not in report['reviewed_units'];m=cropmeta[ident];n=m['pdf_page'];source=next(x for x in imgmeta['images'] if x['pdf_page']==n);old=units[ident]['reading_tibetan'];new=old[:-1]+'། །' if ident!='U00710' else old.replace('གང། །','གང་། །');assert new!=old
 path=ev/f'{ident}.png';shutil.copyfile(w/f'{ident}-native-crop.png',path)
 evidence=[{'path':str(path.relative_to(repo/'diplomatic')),'sha256':sha(path),'pixel_bounds':m['native_bounds'],'native_dimensions':m['native_image_dimensions'],'derivation':'unscaled rectangular crop of original-images.zip native image, no enhancement','source_archive':'editions/adzom-2000/original-images.zip','source_member':source['file'],'source_member_sha256':source['sha256'],'pdf_page':n,'bdrc_image':n+2}]
 if prior:
  pp=repo/'diplomatic/evidence/chapter-01/extension/base-signs-early'/prior;evidence.append({'path':str(pp.relative_to(repo/'diplomatic')),'sha256':sha(pp),'role':'earlier retained crop also visually inspected; fresh native crop controls this judgment'})
 uncertainty='Only the stated terminal sign or tsheg allocation is certified; this is not full punctuation or lexical proofreading. Unicode spacing represents separated strokes, not measured facsimile spacing.'
 locator=f'Adzom 2000 PDF {n}; BDRC I1KG11710 image {n+2}; main text row {m["row"]}; terminal boundary of {ident}'
 r={'id':f'SIGNS-RECOVERY-20260927-{ident}','units':[ident],'original_units':{ident:old},'replacement_units':{ident:new},'finding':'confirmed terminal punctuation mismatch','category':'source punctuation','disposition':'proposed; not integrated','confidence':'high for stated local sign allocation','locator':locator,'observed_strokes':observed,'uncertainty':uncertainty,'evidence':evidence,'source_tibetan_unchanged':units[ident]['source_tibetan'],'context_units':{x:units[x]['reading_tibetan'] for x in [f'U{int(ident[1:])-1:05d}',f'U{int(ident[1:])+1:05d}']}}
 if ident=='U00710':r['existing_intervention_dependency']='SCAN-CH1-LAYER-00710: preserve source annotation separation; proposed original_units intentionally uses the existing main reading, not the original flattened source.'
 report['records'].append(r);report['reviewed_units'].append(ident)
 proposals.append({'id':r['id'],'units':r['units'],'original_units':r['original_units'],'replacement_units':r['replacement_units'],'old':old,'new':new,'rationale':observed,'locator':locator,'evidence':[x['path'] for x in evidence],'evidence_sha256':{x['path']:x['sha256'] for x in evidence},'confidence':{'punctuation':'high for this terminal boundary only'},'source_record':f'reviews/chapter-01/{prefix}.json#{r["id"]}','uncertainty':uncertainty,'status':'proposed; not integrated'})
report['status']='provisional checkpoint; first ten candidates reviewed';report['scope']='Guided fresh image check of first ten integrated_original_unit_changes from recovery packet. No blind or continuous punctuation pass; no English translation QC. Canonical files and Tibetan source are not edited by this reviewer.';report['remaining_integrated_candidates']=[x for x in report['remaining_integrated_candidates'] if x not in notes]
(out/f'{prefix}.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');(out/f'{prefix}-additional-interventions.proposed.json').write_text(json.dumps(proposals,ensure_ascii=False,indent=2)+'\n')
lines=['# Adzom signs recovery review - 2026-09-27','','Provisional checkpoint: ten guided candidate checks. Eight terminal one-to-two shad corrections, one two-to-one correction, and restoration of the visible final tsheg at U00710 are supported by fresh native-image inspection. This reviewer has not edited canonical files or source.','','| Anchor | Locator | Local finding |','| --- | --- | --- |']
for r in report['records']:lines.append(f'| {r["units"][0]} | {r["locator"]} | {r["observed_strokes"]} |')
lines+=['','Each JSON record preserves original and proposed units, exact crop coordinates, native-image and evidence SHA-256, neighboring anchors, and uncertainty. The proposal file is separate for coordinator review/integration.','', 'This is a guided ten-boundary check, not a continuous punctuation pass or chapter-completion certificate. Printed spacing is not measured by the Unicode space used between shads. Five prior integrated candidates, middle candidates, insertions, and U01286 remain outside this checkpoint.','', 'U00710 depends on the existing source-annotation separation: preserve the earlier main/annotation distinction and restore only the visible tsheg in its main reading.']
(out/f'{prefix}.md').write_text('\n'.join(lines)+'\n');print(json.dumps([{x:units[x]['reading_tibetan'], 'new':next(r for r in report['records'] if x in r['units'])['replacement_units'][x]} for x in notes],ensure_ascii=False))
