from pathlib import Path
import json,hashlib,zipfile,io,shutil
from PIL import Image
repo=Path('/Users/mikkokotila/dev/Dra-Thal-Gyur');w=Path(__file__).parent;prefix='signs-recovery-review-20260927';out=repo/'diplomatic/reviews/chapter-01';archive=repo/'diplomatic/recovery/2026-09-27-local/signs-third-batch-paused';archive.mkdir(parents=True,exist_ok=True)
old=json.loads((out/f'{prefix}.json').read_text());m=json.loads((repo/'editions/adzom-2000/image-manifest.json').read_text());z=zipfile.ZipFile(repo/'editions/adzom-2000/original-images.zip');rows=[]
def sha(b):return hashlib.sha256(b).hexdigest()
cores={'U00105':'ལས་ཅན་སྣང་བར་བྱེད་དོན་དུ','U00252':'གཅོད','U00372':'སྣ་ཚོགས་སྤྲོས་པ་དོན་ཡིན་ནོ','U00578':'ཁེངས་ཤིང་ཙནྡན་དྲི','U00594':'འབྲུག་སྒྲོགས་གློག་དམར་ལྕེ་རྣམས་འབྱིན','U00710':'སོ་སོའི་ནུས་པས་བསྒྱུར་བ་གང','U01757':'ཕོ་མོའི་སྡེབས་ཀྱིས་བརྒྱད་དུ་འགྱུར','U02080':'ལྷ་མོའི་མདོག་དང་ཞལ་ཕྱག་ནི'}
for r in old['records']:
 id=r['units'][0];e=r['evidence'][0];b=z.read(e['source_member']);im=Image.open(io.BytesIO(b));replay=im.crop(e['pixel_bounds']);actual=Image.open(repo/'diplomatic'/e['path']);pixel_match=replay.mode==actual.mode and replay.size==actual.size and replay.tobytes()==actual.tobytes();assert pixel_match
 row={'id':id,'historical_record_id':r['id'],'historical_evidence':e['path'],'historical_sha256':e['sha256'],'declared_source_member':e['source_member'],'source_member_sha256_matches_manifest':sha(b)==e['source_member_sha256'],'declared_bounds':e['pixel_bounds'],'crop_pixels_reproduce_exactly':pixel_match,'historical_locator':r['locator'],'disposition':'withdrawn; no adoption authorized by this audit'}
 if id=='U00030':row.update({'target_correspondence':'FAILED','actual_content':'U00025 ending mthun par bshad followed by U00026 opening \'das dang; not U00030.','correct_target_locator':'PDF 4, BDRC image 6, row 1','correct_target_evidence_pending':'recovery_audit opening locator report; work/opening-locator-review/p004-U00030.png','cause':'Wrong page and target phrase identified from overview; expected candidate interpretation carried into unrelated terminal strokes.'})
 elif id=='U00035':row.update({'target_correspondence':'FAILED','actual_content':'U00033 sa dang chu dang me rlung gi followed by U00034 opening \'byung ba; not U00035.','correct_target_locator':'PDF 4, BDRC image 6; U35 starts row 2 end sha khrag and ends row 3 opening bkod pa\'i gzugs med pa\'i','correct_target_evidence_pending':'recovery_audit opening locator report; work/opening-locator-review/p004-U00035.png','cause':'Wrong row selected; terminal sign count was applied to the named candidate without verifying its full lexical anchor.'})
 else:row.update({'target_correspondence':'matched on renewed visual inspection; independent audit pending','observed_core_used_to_identify_target':cores[id],'qualification':'Renewed anchor match is not a re-adoption. Prior sign claims remain withdrawn pending coordinator review.'})
 rows.append(row)
third=json.loads((w/'third-five-crops.json').read_text());saved=[]
for id,info in third.items():
 source=next(x for x in m['images'] if x['pdf_page']==info['pdf_page']);b=z.read(source['file']);expected=Image.open(io.BytesIO(b)).crop(info['native_bounds']);src=w/f'{id}-native-crop.png';actual=Image.open(src);assert expected.tobytes()==actual.tobytes();dest=archive/src.name;shutil.copyfile(src,dest)
 saved.append({'id':id,'path':str(dest.relative_to(repo)),'bytes':dest.stat().st_size,'sha256':sha(dest.read_bytes()),'native_crop':info,'source_archive':'editions/adzom-2000/original-images.zip','source_member':source['file'],'source_member_sha256':source['sha256'],'exact_pixel_reproduction':True,'status':'unfinished candidate material; no final sign judgment or replacement authorized'})
manifest={'status':'paused unfinished third sign-review batch; not canonical evidence for an adopted reading','files':saved,'reason':'All ten earlier sign proposals withdrawn after finding first-two anchor mismatches. Current five target candidates require renewed anchor verification before any proposal. U02489-heading crop is supplemental context.'}
(archive/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');(archive/'README.md').write_text('# Paused third signs batch\n\nSix native crops for five candidate units plus U02489 heading context. Preserved unfinished on 2026-09-27 after earlier target/crop mismatches were discovered. No proposed replacements or final confidence claims accompany these crops. Exact source members, coordinates and SHA-256 are in manifest.json.\n')
audit={'id':'signs-recovery-anchor-audit-20260927','status':'correction and withdrawal audit; does not re-adopt interventions','root_checkpoint_withdrawing_all_ten':'21029ad','finding':'Two of ten historical crops have valid byte/pixel provenance but depict the wrong units. Source extraction and hashes were correct; visual target identification failed. Other eight have been re-identified locally but still need independent review before re-adoption.','root_cause':['The first two locations were inferred from page overviews rather than traced from known page opening through the complete target wording.','Recorded expected Tibetan context came from the supplied transcript; this was incorrectly treated as if it authenticated the pictured target.','Exact hashes and crop coordinates verified image provenance but could not verify that the image depicted the claimed anchor.','Confidence in terminal strokes was reported before resolving target identity; those confidence claims must not be retained as validated review.'],'historical_artifacts_unchanged':True,'records':rows,'unfinished_third_batch_manifest':str((archive/'manifest.json').relative_to(repo)),'third_batch_status':'six crops preserved without proposals; fresh anchor verification required','corrected_opening_crops_seen':'recovery_audit provided correct native PDF4 U30/U35 crops, visually inspected by this reviewer. They are kept separate from historical wrong evidence.'}
(out/'signs-recovery-anchor-audit-20260927.json').write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n');(out/'signs-recovery-anchor-audit-20260927.md').write_text('# Signs anchor audit - 2026-09-27\n\nTwo historical candidate/evidence links failed: U00030.png depicts U00025/U00026; U00035.png depicts U00033/U00034. Both crops exactly reproduce their declared source member and coordinates. The defect is incorrect target identification, not extraction or hashing.\n\nActual U00030 is PDF4 row1; actual U00035 runs from PDF4 row2 end into row3 beginning. The independent opening-locator report supplies corrected evidence.\n\nThe other eight historical targets were re-identified by their lexical sequence during renewed inspection; this audit does not re-adopt their sign proposals. All ten remain withdrawn pending independent review and coordinator decision.\n\nSix unfinished crops for five further candidates plus U02489 heading context are archived separately in recovery/2026-09-27-local/signs-third-batch-paused with exact provenance. No new proposed readings were saved.\n\nRequired safeguard: establish the page opening and complete target wording first; only then assess punctuation. Expected transcript strings and valid image hashes cannot substitute for target identification. Historical reports/crops remain unchanged as superseded records.\n')
print('Saved audit and',len(saved),'paused crops;',sum(x['bytes'] for x in saved),'bytes')
